### ISSUE TITLE
有没有办法一键给所有的dailynote匹配动态图标啊

### ISSUE THREAD

**Issue by HibernalGlow** [Achuan-2/siyuan-plugin-wolai-dynamic-icon#1]
我都是默认图标 或许可以和今日笔记插件配合？

**Comment by Achuan-2** [comment]
可以做，等官方支持文档图标能用动态图标就可以做了，得等3.1.12版本发布

到时候都可以写一个python脚本，批量替换

**Comment by HibernalGlow** [comment]
脚本直接对.sy操作吗 后续日记是不是可以把图标塞模板里？

**Comment by Achuan-2** [comment]
> 脚本直接对.sy操作吗 后续日记是不是可以把图标塞模板里？

嗯，直接修改sy的icon属性
现在dailynote模板就已经可以设置文档图标了，之后也可以设置动态图标，自己选择样式和颜色

**Comment by Achuan-2** [comment]
我写了一个python脚本，可以参考
https://ld246.com/article/1730800370659/comment/1731150419018?r=Achuan-2#comments

**Comment by HibernalGlow** [comment]
> 我写了一个python脚本，可以参考 https://ld246.com/article/1730800370659/comment/1731150419018?r=Achuan-2#comments

嗯 我用上了😋 不过dev版还是用不了模板不知道为啥

**Comment by Achuan-2** [comment]
> > 我写了一个python脚本，可以参考 https://ld246.com/article/1730800370659/comment/1731150419018?r=Achuan-2#comments
> 
> 嗯 我用上了😋 不过dev版还是用不了模板不知道为啥

开发者工具看看用了模板的图标链接是怎样的

**Comment by HibernalGlow** [comment]
![image](https://github.com/user-attachments/assets/1f931d97-28a6-48a2-9ad0-f7b5704ab062)

**Comment by Achuan-2** [comment]
> ![image](https://private-user-images.githubusercontent.com/154863885/384766931-1f931d97-28a6-48a2-9ad0-f7b5704ab062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTUwNTYsIm5iZiI6MTczMTI5NDc1NiwicGF0aCI6Ii8xNTQ4NjM4ODUvMzg0NzY2OTMxLTFmOTMxZDk3LTI4YTYtNDhhMi05YWQwLWY3YjU3MDRhYjA2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwMzEyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmI4MWNjZDI4Yzk2NjY1YjRhMzQ5NjUxOGVlNjY4NDY1Y2M5Y2RkNGY5ZjExMDBhZjhmZWZlN2EyN2QzMzQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fo8Beduwl2FOm65q5ceEYw4Bbg03uugAiGlNCVh4G4Q)

日记模板好像要有纯文字内容，才能设置图标

**Comment by HibernalGlow** [comment]
原来是这样……

**Comment by HibernalGlow** [comment]
搞定了 谢谢

**Comment by Achuan-2** [comment]
> 原来是这样……

你试试，如果有这个问题，可以给思源笔记发个issue，改进下

**Comment by HibernalGlow** [comment]
对了 年和月的有办法自动设置吗

**Comment by Achuan-2** [comment]
> 对了 年和月的有办法自动设置吗

什么意思

**Comment by Achuan-2** [comment]
创建dailynote的时候，父文档的年和月文档也自动设置图标吗，目前不行
